students = [
    {
        "name": "Бабаев Руслан",
        "girl": False,
        "is18": True,
        "glasses": False,
        "brownEyes": True,
        "darkHair": True,
        "siblings": True,
        "pet": True,
        "fromSPb": False,
        "iphone": False,
        "tushavin": False,
        "coffe": False,
        "homefood": False,
        "watch": False,
        "nameVowel": False,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": True,
        "winterOrSpring": True,
        "gaming": False,
        "campus": False,
        "movies": False,
        "anime": True,
    },
    {
        "name": "Шестаков Максим Олегович",
        "girl": False,
        "is18": True,
        "glasses": True,
        "brownEyes": False,
        "darkHair": True,
        "siblings": True,
        "pet": True,
        "fromSPb": False,
        "iphone": True,
        "tushavin": True,
        "coffe": True,
        "homefood": True,
        "watch": True,
        "nameVowel": False,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": True,
        "winterOrSpring": True,
        "gaming": False,
        "campus": False,
        "movies": True,
        "anime": False,
    },
    {
        "name": "Боженко Мария Александровна",
        "girl": True,
        "is18": False,
        "glasses": True,
        "brownEyes": True,
        "darkHair": True,
        "siblings": False,
        "pet": True,
        "fromSPb": True,
        "iphone": True,
        "tushavin": True,
        "coffe": True,
        "homefood": False,
        "watch": False,
        "nameVowel": False,
        "pizza": False,
        "smoke": False,
        "heightOver175": False,
        "partner": False,
        "winterOrSpring": False,
        "gaming": False,
        "campus": False,
        "movies": True,
        "anime": True,
    },
    {
        "name": "Шишминцев Дмитрий Владимирович",
        "girl": False,
        "is18": True,
        "glasses": True,
        "brownEyes": False,
        "darkHair": False,
        "siblings": True,
        "pet": True,
        "fromSPb": True,
        "iphone": True,
        "tushavin": True,
        "coffe": False,
        "homefood": False,
        "watch": False,
        "nameVowel": False,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": True,
        "winterOrSpring": True,
        "gaming": False,
        "campus": False,
        "movies": False,
        "anime": False,
    },
    {
        "name": "Затикян Сергей Арменович",
        "girl": False,
        "is18": True,
        "glasses": True,
        "brownEyes": True,
        "darkHair": True,
        "siblings": True,
        "pet": True,
        "fromSPb": True,
        "iphone": True,
        "tushavin": True,
        "coffe": True,
        "homefood": True,
        "watch": True,
        "nameVowel": False,
        "pizza": True,
        "smoke": True,
        "heightOver175": True,
        "partner": True,
        "winterOrSpring": False,
        "gaming": False,
        "campus": False,
        "movies": True,
        "anime": False,
    },
    {
        "name": "Шаллиева Вера Владимировна",
        "girl": True,
        "is18": False,
        "glasses": True,
        "brownEyes": False,
        "darkHair": False,
        "siblings": True,
        "pet": True,
        "fromSPb": True,
        "iphone": False,
        "tushavin": True,
        "coffe": False,
        "homefood": False,
        "watch": False,
        "nameVowel": False,
        "pizza": False,
        "smoke": False,
        "heightOver175": False,
        "partner": False,
        "winterOrSpring": False,
        "gaming": False,
        "campus": False,
        "movies": True,
        "anime": True,
    },
    {
        "name": "Смирнов Игорь Иванович",
        "girl": False,
        "is18": True,
        "glasses": False,
        "brownEyes": True,
        "darkHair": True,
        "siblings": False,
        "pet": False,
        "fromSPb": False,
        "iphone": False,
        "tushavin": True,
        "coffe": False,
        "homefood": True,
        "watch": True,
        "nameVowel": True,
        "pizza": True,
        "smoke": False,
        "heightOver175": False,
        "partner": False,
        "winterOrSpring": True,
        "gaming": True,
        "campus": True,
        "movies": True,
        "anime": False,
    },
    {
        "name": "Абдулов Илья Александрович",
        "girl": False,
        "is18": True,
        "glasses": True,
        "brownEyes": False,
        "darkHair": False,
        "siblings": True,
        "pet": False,
        "fromSPb": False,
        "iphone": True,
        "tushavin": False,
        "coffe": False,
        "homefood": True,
        "watch": False,
        "nameVowel": True,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": False,
        "winterOrSpring": False,
        "gaming": True,
        "campus": False,
        "movies": True,
        "anime": False,
    },
    {
        "name": "Кремпольская Екатерина Александровна",
        "girl": True,
        "is18": True,
        "glasses": True,
        "brownEyes": False,
        "darkHair": False,
        "siblings": True,
        "pet": True,
        "fromSPb": False,
        "iphone": False,
        "tushavin": False,
        "coffe": False,
        "homefood": True,
        "watch": False,
        "nameVowel": True,
        "pizza": False,
        "smoke": False,
        "heightOver175": False,
        "partner": False,
        "winterOrSpring": True,
        "gaming": False,
        "campus": False,
        "movies": False,
        "anime": True,
    },
    {
        "name": "Касьяненко Вера Михайловна",
        "girl": True,
        "is18": False,
        "glasses": False,
        "brownEyes": True,
        "darkHair": True,
        "siblings": True,
        "pet": True,
        "fromSPb": True,
        "iphone": False,
        "tushavin": True,
        "coffe": True,
        "homefood": True,
        "watch": True,
        "nameVowel": False,
        "pizza": True,
        "smoke": False,
        "heightOver175": False,
        "partner": True,
        "winterOrSpring": True,
        "gaming": False,
        "campus": False,
        "movies": True,
        "anime": True,
    },
    {
        "name": "Язев Григорий",
        "girl": False,
        "is18": False,
        "glasses": False,
        "brownEyes": False,
        "darkHair": False,
        "siblings": True,
        "pet": True,
        "fromSPb": True,
        "iphone": False,
        "tushavin": True,
        "coffe": False,
        "homefood": False,
        "watch": False,
        "nameVowel": False,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": False,
        "winterOrSpring": True,
        "gaming": False,
        "campus": False,
        "movies": False,
        "anime": True,
    },
    {
        "name": "Алексеев Тимофей Юрьевич",
        "girl": False,
        "is18": False,
        "glasses": False,
        "brownEyes": False,
        "darkHair": False,
        "siblings": True,
        "pet": True,
        "fromSPb": False,
        "iphone": True,
        "tushavin": False,
        "coffe": True,
        "homefood": True,
        "watch": True,
        "nameVowel": False,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": False,
        "winterOrSpring": False,
        "gaming": False,
        "campus": True,
        "movies": True,
        "anime": False,
    },
    {
        "name": "Горлов Игорь",
        "girl": False,
        "is18": True,
        "glasses": False,
        "brownEyes": False,
        "darkHair": True,
        "siblings": True,
        "pet": True,
        "fromSPb": False,
        "iphone": False,
        "tushavin": False,
        "coffe": False,
        "homefood": True,
        "watch": False,
        "nameVowel": True,
        "pizza": True,
        "smoke": False,
        "heightOver175": False,
        "partner": False,
        "winterOrSpring": True,
        "gaming": True,
        "campus": True,
        "movies": True,
        "anime": True,
    },
    {
        "name": "Садовая Анастасия Романовна",
        "girl": True,
        "is18": False,
        "glasses": False,
        "brownEyes": False,
        "darkHair": False,
        "siblings": True,
        "pet": True,
        "fromSPb": False,
        "iphone": False,
        "tushavin": False,
        "coffe": True,
        "homefood": True,
        "watch": True,
        "nameVowel": True,
        "pizza": False,
        "smoke": False,
        "heightOver175": False,
        "partner": False,
        "winterOrSpring": True,
        "gaming": False,
        "campus": True,
        "movies": False,
        "anime": False,
    },
    {
        "name": "Надери Мариам Шаховна ",
        "girl": True,
        "is18": True,
        "glasses": True,
        "brownEyes": False,
        "darkHair": True,
        "siblings": True,
        "pet": True,
        "fromSPb": True,
        "iphone": False,
        "tushavin": True,
        "coffe": False,
        "homefood": True,
        "watch": False,
        "nameVowel": False,
        "pizza": False,
        "smoke": False,
        "heightOver175": False,
        "partner": False,
        "winterOrSpring": True,
        "gaming": False,
        "campus": False,
        "movies": False,
        "anime": True,
    },
    {
        "name": "Оншин Дмитрий Николаевич",
        "girl": False,
        "is18": True,
        "glasses": False,
        "brownEyes": False,
        "darkHair": True,
        "siblings": True,
        "pet": False,
        "fromSPb": True,
        "iphone": True,
        "tushavin": False,
        "coffe": True,
        "homefood": True,
        "watch": True,
        "nameVowel": False,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": True,
        "winterOrSpring": True,
        "gaming": True,
        "campus": False,
        "movies": True,
        "anime": False,
    },
    {
        "name": "Петрова Наталья Глебовна ",
        "girl": True,
        "is18": True,
        "glasses": True,
        "brownEyes": False,
        "darkHair": False,
        "siblings": False,
        "pet": False,
        "fromSPb": True,
        "iphone": True,
        "tushavin": False,
        "coffe": False,
        "homefood": True,
        "watch": True,
        "nameVowel": False,
        "pizza": False,
        "smoke": False,
        "heightOver175": True,
        "partner": True,
        "winterOrSpring": True,
        "gaming": False,
        "campus": False,
        "movies": False,
        "anime": False,
    },
    {
        "name": "Кабдулвахитов Эмир Ержанович ",
        "girl": False,
        "is18": True,
        "glasses": True,
        "brownEyes": True,
        "darkHair": True,
        "siblings": True,
        "pet": False,
        "fromSPb": False,
        "iphone": True,
        "tushavin": True,
        "coffe": True,
        "homefood": False,
        "watch": False,
        "nameVowel": True,
        "pizza": True,
        "smoke": True,
        "heightOver175": True,
        "partner": False,
        "winterOrSpring": False,
        "gaming": True,
        "campus": True,
        "movies": True,
        "anime": True,
    },
    {
        "name": "Авокадо Ева Сергеевна",
        "girl": True,
        "is18": False,
        "glasses": True,
        "brownEyes": False,
        "darkHair": True,
        "siblings": False,
        "pet": True,
        "fromSPb": False,
        "iphone": False,
        "tushavin": True,
        "coffe": False,
        "homefood": True,
        "watch": False,
        "nameVowel": True,
        "pizza": True,
        "smoke": False,
        "heightOver175": False,
        "partner": True,
        "winterOrSpring": False,
        "gaming": True,
        "campus": False,
        "movies": False,
        "anime": False,
    },
    {
        "name": "Царёв Александр Сергеевич",
        "girl": False,
        "is18": True,
        "glasses": False,
        "brownEyes": False,
        "darkHair": False,
        "siblings": False,
        "pet": False,
        "fromSPb": True,
        "iphone": True,
        "tushavin": True,
        "coffe": False,
        "homefood": False,
        "watch": False,
        "nameVowel": True,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": False,
        "winterOrSpring": False,
        "gaming": True,
        "campus": False,
        "movies": True,
        "anime": False,
    },
    {
        "name": "Адрат Олеся Александровна ",
        "girl": True,
        "is18": True,
        "glasses": False,
        "brownEyes": False,
        "darkHair": False,
        "siblings": True,
        "pet": True,
        "fromSPb": True,
        "iphone": True,
        "tushavin": False,
        "coffe": False,
        "homefood": True,
        "watch": False,
        "nameVowel": True,
        "pizza": False,
        "smoke": False,
        "heightOver175": True,
        "partner": True,
        "winterOrSpring": False,
        "gaming": False,
        "campus": False,
        "movies": True,
        "anime": False,
    },
    {
        "name": "Комелин Глеб Александрович",
        "girl": False,
        "is18": True,
        "glasses": False,
        "brownEyes": False,
        "darkHair": True,
        "siblings": True,
        "pet": True,
        "fromSPb": False,
        "iphone": True,
        "tushavin": True,
        "coffe": True,
        "homefood": True,
        "watch": False,
        "nameVowel": False,
        "pizza": False,
        "smoke": True,
        "heightOver175": False,
        "partner": False,
        "winterOrSpring": False,
        "gaming": True,
        "campus": True,
        "movies": False,
        "anime": False,
    },
    {
        "name": "Миляев Дмитрий Дмитриевич",
        "girl": False,
        "is18": True,
        "glasses": True,
        "brownEyes": False,
        "darkHair": False,
        "siblings": False,
        "pet": True,
        "fromSPb": False,
        "iphone": True,
        "tushavin": False,
        "coffe": True,
        "homefood": True,
        "watch": False,
        "nameVowel": False,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": True,
        "winterOrSpring": False,
        "gaming": False,
        "campus": False,
        "movies": True,
        "anime": False,
    },
    {
        "name": "Телунц Эдуард Рубенович",
        "girl": False,
        "is18": True,
        "glasses": False,
        "brownEyes": True,
        "darkHair": True,
        "siblings": True,
        "pet": False,
        "fromSPb": False,
        "iphone": False,
        "tushavin": False,
        "coffe": False,
        "homefood": True,
        "watch": False,
        "nameVowel": True,
        "pizza": True,
        "smoke": False,
        "heightOver175": True,
        "partner": False,
        "winterOrSpring": False,
        "gaming": False,
        "campus": True,
        "movies": False,
        "anime": False,
    },
    {
        "name": "Белисов Глеб",
        "girl": False,
        "is18": True,
        "glasses": False,
        "brownEyes": True,
        "darkHair": False,
        "siblings": True,
        "pet": True,
        "fromSPb": False,
        "iphone": True,
        "tushavin": True,
        "coffe": True,
        "homefood": True,
        "watch": False,
        "nameVowel": False,
        "pizza": False,
        "smoke": False,
        "heightOver175": False,
        "partner": False,
        "winterOrSpring": False,
        "gaming": True,
        "campus": True,
        "movies": False,
        "anime": True,
    },
    {
        "name": "Конопля Алексей Константинович ",
        "girl": False,
        "is18": False,
        "glasses": True,
        "brownEyes": False,
        "darkHair": False,
        "siblings": True,
        "pet": True,
        "fromSPb": True,
        "iphone": True,
        "tushavin": True,
        "coffe": False,
        "homefood": False,
        "watch": False,
        "nameVowel": True,
        "pizza": False,
        "smoke": True,
        "heightOver175": True,
        "partner": False,
        "winterOrSpring": True,
        "gaming": True,
        "campus": False,
        "movies": True,
        "anime": True,
    },
]
